# Generated by Django 3.1.7 on 2021-03-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolnn", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingpass",
            name="end_datetime",
        ),
        migrations.RemoveField(
            model_name="trainingpass",
            name="start_datetime",
        ),
        migrations.AddField(
            model_name="trainingpass",
            name="duration_seconds",
            field=models.BigIntegerField(default=0),
        ),
    ]
