stages:
  - test
  - deploy

mypy-typing-check:
  stage: test
  tags:
    - mypy
  script:
    - python3 -m mypy . --ignore-missing-imports

bandit-security-check:
  stage: test
  tags:
    - bandit
  script:
    - python3 -m bandit -r .  --config .bandit.yaml

pylint-style-check:
  stage: test
  tags:
    - pylint
  script:
    - python3 -m pylint schoolnn --ignore "schoolnn/migrations"
      --disable "too-many-ancestors,no-member,too-few-public-methods"
    - python3 -m pylint schoolnn_app

flake8-style-check:
  stage: test
  tags:
    - flake8
  script:
    - python3 -m flake8 . --exclude "schoolnn/migrations/*"

