stages:
  - test
  - deploy

mypy-typing-check:
  stage: test
  tags:
    - mypy
  script:
    - python3 -m mypy . --ignore-missing-imports

bandit-security-check:
  stage: test
  tags:
    - bandit
  script:
    - python3 -m bandit -r . --config .bandit.yaml

black-style-check:
  stage: test
  tags:
    - black
  script:
    - python3 -m black . --line-length 79 --check

flake8-style-check:
  stage: test
  tags:
    - flake8
  script:
    - python3 -m flake8 . --exclude "schoolnn/migrations/*"

pytest-unittest:
  image: python:3.8-buster
  stage: test
  variables:
    WORKON_HOME: .pipenv/venvs
    PIP_CACHE_DIR: .pipenv/pipcache
    SECRET_KEY: CHANGE_ME_IN_PRODUCTION
  cache:
    key: pipenv
    paths:
      - .pipenv
  tags:
    - pytest
    - tensorflow
  before_script:
    - apt update && apt install -y libgl1-mesa-glx
    - pip install pipenv
    - pipenv install --dev
  script:
    - pipenv run python3 -m pytest . --confcutdir tests
