stages:
  - test
  - deploy

mypy-typing-check:
  stage: test
  tags:
    - mypy
  script:
    - python3 -m mypy . --ignore-missing-imports

bandit-security-check:
  stage: test
  tags:
    - bandit
  script:
    - python3 -m bandit -r .  --config .bandit.yaml

black-style-check:
  stage: test
  tags:
    - black
  script:
    - python3 -m black . --check

flake8-style-check:
  stage: test
  tags:
    - flake8
  script:
    - python3 -m flake8 . --exclude "schoolnn/migrations/*"

